name: CI and Docker Push

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      IMAGE_NAME: flask_todo_app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run tests with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app
        continue-on-error: true
        id: test_step

      - name: Check test result
        if: steps.test_step.outcome != 'success'
        run: echo "❌ הבדיקות נכשלו או הקובץ לא נשלח ל-Docker Hub"

      - name: Login to Docker Hub
        if: steps.test_step.outcome == 'success'
        run: echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin

      - name: Build Docker image
        if: steps.test_step.outcome == 'success'
        run: docker build -t ${DOCKER_USER}/${IMAGE_NAME}:latest .

      - name: Push Docker image
        if: steps.test_step.outcome == 'success'
        run: docker push ${DOCKER_USER}/${IMAGE_NAME}:latest
